name: QA

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - develop
      - main

env:
  CACHE_KEY: ${{ github.sha }}-${{ github.run_number }}-${{ github.run_attempt }}
  CACHE_PATH: ./*

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18.13.0
        pnpm-version:
          - 7.26.3
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm v${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}
      - name: Setup node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: pnpm install
      - name: Cache setup
        uses: actions/cache@v3
        id: cache-setup
        with:
          key: ${{ env.CACHE_KEY }}
          path: ${{ env.CACHE_PATH }}
      - name: Set node-version
        id: set-node-version
        run: echo "node-version=${{ matrix.node-version }}" >> $GITHUB_OUTPUT
      - name: Set pnpm-version
        id: set-pnpm-version
        run: echo "pnpm-version={{ matrix.pnpm-version }}" >> $GITHUB_OUTPUT
  commitlint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ needs.setup.outputs.pnpm-version }}
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: ${{ needs.setup.outputs.node-version }}
      - name: Restore setup
        uses: actions/cache@v3
        id: restore-setup
        with:
          key: ${{ env.CACHE_KEY }}
          path: ${{ env.CACHE_PATH }}
      - name: Run commitlint
        run: pnpm commitlint --from=${{ github.sha }}
  tsc:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ needs.setup.outputs.pnpm-version }}
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: ${{ needs.setup.outputs.node-version }}
      - name: Restore setup
        uses: actions/cache@v3
        id: restore-setup
        with:
          key: ${{ env.CACHE_KEY }}
          path: ${{ env.CACHE_PATH }}
      - name: Run tsc
        run: pnpm run ts
  eslint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ needs.setup.outputs.pnpm-version }}
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: ${{ needs.setup.outputs.node-version }}
      - name: Restore setup
        uses: actions/cache@v3
        id: restore-setup
        with:
          key: ${{ env.CACHE_KEY }}
          path: ${{ env.CACHE_PATH }}
      - name: Run eslint
        run: pnpm run eslint
  stylelint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ needs.setup.outputs.pnpm-version }}
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: ${{ needs.setup.outputs.node-version }}
      - name: Restore setup
        uses: actions/cache@v3
        id: restore-setup
        with:
          key: ${{ env.CACHE_KEY }}
          path: ${{ env.CACHE_PATH }}
      - name: Run stylelint
        run: pnpm run stylelint
  prettier:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ needs.setup.outputs.pnpm-version }}
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          cache: pnpm
          node-version: ${{ needs.setup.outputs.node-version }}
      - name: Restore setup
        uses: actions/cache@v3
        id: restore-setup
        with:
          key: ${{ env.CACHE_KEY }}
          path: ${{ env.CACHE_PATH }}
      - name: Run prettier
        run: pnpm run prettier
